#
# pyproject.toml
#
# Usage:
#   python -m build
#   python -m build --wheel
#   python -m build --sdist
#
#   hatch build
#   hatch run test:pytest
#


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "nrtest-epanet"
# version = "0.1.0"
description = "A brief description of your project."
# sreadme = "README.md"
authors = [
  { name = "Your Name", email = "your.email@example.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dynamic = ["version"]
dependencies = [
    "header_detail_footer>=2.3",
    "nrtest>=0.2.4",
    "numpy>=1.7.0",
    "epanet-toolkit"
]


[tool.hatch.build.targets.wheel]
packages = ["nrtest_epanet"]


[tool.hatch.metadata]
allow-dynamic = ["version"]
allow-direct-references = true


[tool.hatch.version]
path = "nrtest_epanet/__init__.py"


[project.scripts]
report-diff = "nrtest_epanet.cli:main"


[project.entry-points."nrtest.compare"]
epanet_allclose = "nrtest_epanet:epanet_allclose_compare"
epanet_mincdd = "nrtest_epanet:epanet_mincdd_compare"
epanet_report = "nrtest_epanet:epanet_report_compare"


# TODO: To work, this needs to run twice for some reason?
[tool.hatch.envs.test]
dependencies = [
  "epanet-toolkit @ {root:parent:uri}/epanet-toolkit/",
  "nrtest-epanet @ {root:uri}",
  "pytest"
]
