[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "nrtest-epanet"
# version = "0.1.0"
description = "A brief description of your project."
# sreadme = "README.md"
authors = [
  { name = "Your Name", email = "your.email@example.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dynamic = ["version"]
dependencies = [
    "header_detail_footer>=2.3",
    "nrtest>=0.2.4",
    "numpy>=1.7.0",
#    "epanet_toolkit"
]


[tool.hatch.dependencies]
# Specify the local wheel file (path to the .whl file)
epanet_toolkit = { path = "../epanet-toolkit/epanet_toolkit-0.5.0-cp39-cp39-macosx_10_13_x86_64.whl" }


[tool.hatch.build.targets.wheel]
packages = ["nrtest_epanet"]


[tool.hatch.metadata]
allow-dynamic = ["version"]


[tool.hatch.version]
path = "nrtest_epanet/__init__.py"


[project.scripts]
report-diff = "nrtest_epanet.cli:main"


[project.entry-points."nrtest.compare"]
epanet_allclose = "nrtest_epanet:epanet_allclose_compare"
epanet_mincdd = "nrtest_epanet:epanet_mincdd_compare"
epanet_report = "nrtest_epanet:epanet_report_compare"


[tool.hatch.envs.default]
dependencies = [
  "pytest"
]

[tool.hatch.envs.default.scripts]
test = "pytest"
