
#
# pyproject.toml
#
# Usage:
#   python -m build
#   hatch run test:pytest
#


[build-system]
requires = [
    "scikit-build-core",
    "swig == 4.2.1"
]
build-backend = "scikit_build_core.build"


[tool.scikit-build]
minimum-version = "0.10"
build.verbose = true
logging.level = "INFO"


[tool.scikit-build.wheel]
exclude = [
    "/bin",
    "/bindings",
    "/cmake",
    "/include",
    "/libs",
    "*.i",
    "AUTHORS",
    "CMakeLists.txt",
    "LICENSE.txt",
    "ReleaseNotes.md"
]


[project]
name = "epanet-toolkit"
version = "0.5.0"
description = "Python bindings for the EPANET Toolkit"
readme = { file = "README.md", content-type = "text/markdown" }
url = "https://github.com/EPANET-Project/epanet-python"
authors = [
    { name = "Michael E. Tryby", email = "tryby.michael@epa.gov"}
]
license = {text = "CC0-1.0"}
requires-python = ">=3.7"
dependencies = [
    "aenum==3.0.0"
]
classifiers=[
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C",
    "Development Status :: 4 - Beta",
]



[tool.hatch.envs.test]
dependencies = [
   "pytest",
   "numpy",
   "epanet-toolkit @ {root:uri}"
]
