name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [windows-2016, macos-10.15]
          py: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install build requirements
        if: ${{ contains(matrix.os, 'windows') }}
        run: choco install swig

      - if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt-get install swig

      - if: ${{ contains(matrix.os, 'macos') }}
        run: brew install libomp swig

      - name: Build wheel
        run: pip wheel --wheel-dir=./dist ./epanet-toolkit

      - name: Test wheel
        run: |
          pip install pytest numpy
          pip install --no-index --find-links=./dist epanet-toolkit
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/epanet_toolkit*.whl